apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment-quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deployment-quiz
  template:
    metadata:
      labels:
        app: k8s-deployment-quiz
    spec:
      containers:
      - name: k8s-deployment-quiz
        image: calavelas/k8s-deployment-quiz:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"