apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment-quiz-service
spec:
  selector:
    app: k8s-deployment-quiz # This should match the label of your deployment pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 # Assuming your Flask app is running on port 80 inside the container
  type: ClusterIP # Or use "NodePort" or "LoadBalancer" depending on your needs
